//! Invariant 1: a record document reader answers, it never panics.
//!
//! A stored record document is untrusted input. The reader's contract is that
//! any byte sequence at a record path either reads back as a record of that
//! kind or is refused with a `record.*` diagnostic, that the refusal names the
//! shape of the failure and never the bytes, and that a document larger than
//! the record cap is refused on the opened handle before its bytes are
//! allocated.
//!
//! Random bytes exercise only the refusing arm: a generated byte sequence is
//! never a valid record. So the properties here come in three parts. Random
//! bytes cover the reader's tolerance of arbitrary input, a generated valid
//! record carrying a difference the reader is documented to ignore must still
//! read back, and one carrying a difference the reader does check must be
//! refused. Together they reach both arms by construction rather than by luck.

use std::fs;
use std::path::Path;

use proptest::prelude::*;

use openpapir_core::archive::import::ImportEvent;
use openpapir_core::archive::limits;
use openpapir_core::archive::{Archive, MARKER_FILE};
use openpapir_core::error::codes;
use openpapir_core::records::association::Association;
use openpapir_core::records::case::Case;
use openpapir_core::records::document::{self, Record};
use openpapir_core::records::receipt::Receipt;
use openpapir_core::records::submission::Submission;

use super::support::{self, Capped};

/// The identifier every generated document is stored under.
const ID: &str = "0123456789abcdef0123456789abcdef";

/// The codes a record reader is allowed to answer a bad document with.
const READER_CODES: [&str; 3] = [
    codes::RECORD_MALFORMED,
    codes::RECORD_NOT_FOUND,
    codes::INPUT_CAP_RECORD_SIZE,
];

/// The top-level capped fields of each kind.
///
/// The field-length damages set every one of them to exactly its cap and then
/// to one step over, which the reader must tolerate either way: a length cap
/// belongs to the write path and the read path does not re-check it. A case's
/// tags carry two caps at once, 64 bytes each and 32 of them, so the list is
/// filled to both and then to one past both. A kind whose only capped text is
/// nested inside a list would pass an empty slice here and the two damages
/// would leave its document alone.
const CASE_FIELDS: [Capped; 2] = [Capped::Text("title", 200), Capped::TextList("tags", 64, 32)];
const SUBMISSION_FIELDS: [Capped; 1] = [Capped::Text("description", 1024)];
const RECEIPT_FIELDS: [Capped; 1] = [Capped::Text("label", 200)];
const ASSOCIATION_FIELDS: [Capped; 1] = [Capped::Text("statement", 512)];
const EVENT_FIELDS: [Capped; 1] = [Capped::Text("original_filename", 255)];

/// Store one document at this kind's record path and read it back.
///
/// Returns whether the reader answered `Ok`, so a property can assert which
/// arm it reached instead of accepting either. The document is cleared again,
/// so one archive serves every kind in a case.
fn stored_and_read<R: Record>(root: &Path, document: &str) -> Result<bool, TestCaseError> {
    let path = root.join(R::DIRECTORY).join(format!("{ID}.json"));
    fs::write(&path, document).expect("a generated document is stored");
    let read = read_back::<R>(root)?;
    fs::remove_file(&path).expect("the document is cleared for the next kind");
    Ok(read)
}

/// Read one kind back and assert the reader's whole contract for it.
fn read_back<R: Record>(root: &Path) -> Result<bool, TestCaseError> {
    let answered = match document::read_record::<R>(root, ID, "record_id") {
        Ok(record) => {
            prop_assert_eq!(
                record.id(),
                ID,
                "a record that reads back names its own file"
            );
            prop_assert_eq!(record.record_kind(), R::KIND);
            true
        }
        Err(refusal) => {
            prop_assert!(
                READER_CODES.contains(&refusal.code),
                "a record reader answered with an undocumented code"
            );
            support::details_are_permitted(&refusal)?;
            support::exit_code_is_bucketed(&refusal)?;
            false
        }
    };
    match document::list_records::<R>(root) {
        Ok(records) => {
            prop_assert_eq!(records.len(), usize::from(answered));
            prop_assert!(answered, "a listing that reads is a record that reads");
        }
        Err(refusal) => {
            prop_assert_eq!(refusal.code, codes::RECORD_MALFORMED);
            prop_assert!(!answered, "a listing that refuses is a record that refuses");
        }
    }
    Ok(answered)
}

/// An empty archive layout with one record directory per kind.
fn layout() -> tempfile::TempDir {
    let root = tempfile::tempdir().expect("a temporary archive root");
    support::record_directories(root.path());
    root
}

proptest! {
    #![proptest_config(support::config(256))]

    /// Any byte sequence stored at a record path reads back as that record or
    /// is refused with a documented `record.*` code, for every record kind.
    #[test]
    fn any_bytes_at_a_record_path_read_or_are_refused(
        bytes in proptest::collection::vec(any::<u8>(), 0..512),
    ) {
        let root = layout();
        for directory in [
            Case::DIRECTORY,
            Submission::DIRECTORY,
            Receipt::DIRECTORY,
            Association::DIRECTORY,
            ImportEvent::DIRECTORY,
        ] {
            fs::write(root.path().join(directory).join(format!("{ID}.json")), &bytes)
                .expect("a generated document is stored");
        }
        read_back::<Case>(root.path())?;
        read_back::<Submission>(root.path())?;
        read_back::<Receipt>(root.path())?;
        read_back::<Association>(root.path())?;
        read_back::<ImportEvent>(root.path())?;
    }

    /// A valid record document carrying a difference the reader is documented
    /// to ignore still reads back, for every kind. This is the arm random
    /// bytes can never reach.
    #[test]
    fn a_tolerated_difference_still_reads_back(
        case in support::case_record(),
        submission in support::submission_record(),
        receipt in support::receipt_record(),
        association in support::association_record(),
        event in support::import_event_record(),
        damage in support::tolerated_damage(),
        key in proptest::sample::select(support::REQUIRED_KEYS.to_vec()),
    ) {
        prop_assert!(damage.tolerated());
        let root = layout();
        prop_assert!(stored_and_read::<Case>(
            root.path(),
            &support::damaged_document(&case, ID, damage, &CASE_FIELDS, key),
        )?);
        prop_assert!(stored_and_read::<Submission>(
            root.path(),
            &support::damaged_document(&submission, ID, damage, &SUBMISSION_FIELDS, key),
        )?);
        prop_assert!(stored_and_read::<Receipt>(
            root.path(),
            &support::damaged_document(&receipt, ID, damage, &RECEIPT_FIELDS, key),
        )?);
        prop_assert!(stored_and_read::<Association>(
            root.path(),
            &support::damaged_document(&association, ID, damage, &ASSOCIATION_FIELDS, key),
        )?);
        prop_assert!(stored_and_read::<ImportEvent>(
            root.path(),
            &support::damaged_document(&event, ID, damage, &EVENT_FIELDS, key),
        )?);
    }

    /// A valid record document carrying a difference the reader does check is
    /// refused, never repaired, skipped, or guessed at.
    #[test]
    fn a_breaking_difference_is_refused(
        case in support::case_record(),
        submission in support::submission_record(),
        receipt in support::receipt_record(),
        association in support::association_record(),
        event in support::import_event_record(),
        damage in support::breaking_damage(),
        key in proptest::sample::select(support::REQUIRED_KEYS.to_vec()),
    ) {
        prop_assert!(!damage.tolerated());
        let root = layout();
        prop_assert!(!stored_and_read::<Case>(
            root.path(),
            &support::damaged_document(&case, ID, damage, &CASE_FIELDS, key),
        )?);
        prop_assert!(!stored_and_read::<Submission>(
            root.path(),
            &support::damaged_document(&submission, ID, damage, &SUBMISSION_FIELDS, key),
        )?);
        prop_assert!(!stored_and_read::<Receipt>(
            root.path(),
            &support::damaged_document(&receipt, ID, damage, &RECEIPT_FIELDS, key),
        )?);
        prop_assert!(!stored_and_read::<Association>(
            root.path(),
            &support::damaged_document(&association, ID, damage, &ASSOCIATION_FIELDS, key),
        )?);
        prop_assert!(!stored_and_read::<ImportEvent>(
            root.path(),
            &support::damaged_document(&event, ID, damage, &EVENT_FIELDS, key),
        )?);
    }

    /// Any byte sequence in the archive marker opens the archive or is refused
    /// with an `archive.*` diagnostic. The marker is the first untrusted
    /// document every operation reads.
    #[test]
    fn any_bytes_in_the_marker_open_the_archive_or_are_refused(
        bytes in proptest::collection::vec(any::<u8>(), 0..256),
    ) {
        let root = tempfile::tempdir().expect("a temporary archive root");
        openpapir_core::archive::init(root.path()).expect("an archive is created");
        fs::write(root.path().join(MARKER_FILE), &bytes).expect("a marker is stored");

        if let Err(refusal) = Archive::open_read_only(root.path()) {
            prop_assert!(
                refusal.code.starts_with("archive."),
                "a marker that cannot be read is an archive refusal"
            );
            support::details_are_permitted(&refusal)?;
            support::exit_code_is_bucketed(&refusal)?;
        }
    }
}

proptest! {
    #![proptest_config(support::config(12))]

    /// The record cap is a boundary the reader honours from both sides. A
    /// document over the cap is refused on the opened handle, before its bytes
    /// are read; one at or under it is read and only then refused on its
    /// content, which is what proves the cap is a cap and not a refusal to
    /// look at all.
    #[test]
    fn the_record_cap_refuses_only_what_is_over_it(offset in -2048_i64..=2048) {
        let root = layout();
        let path = root.path().join(Case::DIRECTORY).join(format!("{ID}.json"));
        let size = limits::MAX_RECORD_BYTES
            .checked_add_signed(offset)
            .expect("the offset stays inside the cap's neighbourhood");
        fs::write(&path, vec![b'{'; usize::try_from(size).expect("the cap fits in memory")])
            .expect("a generated document is stored");

        let refusal = document::read_record::<Case>(root.path(), ID, "case_id")
            .expect_err("a run of braces is never a record");
        if size > limits::MAX_RECORD_BYTES {
            prop_assert_eq!(refusal.code, codes::INPUT_CAP_RECORD_SIZE);
            prop_assert_eq!(refusal.exit_code(), 3);
        } else {
            prop_assert_eq!(
                refusal.code,
                codes::RECORD_MALFORMED,
                "a document inside the cap is read and refused on its content"
            );
        }
        support::details_are_permitted(&refusal)?;

        let refusal = document::list_records::<Case>(root.path())
            .expect_err("a listing reports the directory's condition");
        prop_assert_eq!(refusal.code, codes::RECORD_MALFORMED);
    }
}
