#!/usr/bin/env bash
# Stage the contents of one release archive, then check the staged layout.
#
# The release workflow calls this once per target, with the binary it just
# built, and the CI test job calls it on every pull request with the binary
# from its own release build. Both call this one script, so the layout a
# release ships is the layout every pull request exercises, without a tag.
#
# The completion scripts and the man page are generated by the built binary of
# that target, from the command definition it was built with, so they can
# never describe commands the archived binary does not have.
#
# Usage:
#   scripts/package-release.sh <binary> <staging directory>
#   scripts/package-release.sh --describe
#
# `--describe` prints the sentence that names what an archive holds. The
# release job and the dry-run summary print it, so the description cannot
# drift from what this script stages.
set -euo pipefail

# The completion script names are the ones each shell looks for, which is what
# the manual instructions in README.md redirect to.
readonly SHELLS="bash:openpapir.bash zsh:_openpapir fish:openpapir.fish"
readonly MORE_SHELLS="powershell:_openpapir.ps1 elvish:openpapir.elv"
readonly MAN_PAGE="man/man1/openpapir.1"

describe() {
  cat <<'EOF'
Each archive holds the `openpapir` binary, `LICENSE`, `README.md`,
`CHANGELOG.md`, a shell completion script for each of `bash`, `zsh`, `fish`,
`powershell`, and `elvish` under `completions/`, and the man page at
`man/man1/openpapir.1`, under one directory named
`openpapir-<version>-<target>`. The completion scripts and the man page are
generated by the built binary of that target. The `<archive>.sha256` file
beside each archive covers the archive as a whole, so it covers them too.
EOF
}

fail() {
  echo "package-release: $1" >&2
  exit 1
}

# Every staged file has to exist and hold something: an empty completion
# script is a generator that failed quietly, not a shipped file.
check_present() {
  local path="$1"
  [ -f "$path" ] || fail "missing from the staged archive: $2"
  [ -s "$path" ] || fail "empty in the staged archive: $2"
}

main() {
  if [ "${1:-}" = "--describe" ]; then
    describe
    return 0
  fi
  [ "$#" -eq 2 ] || fail "usage: package-release.sh <binary> <staging directory>"

  local binary="$1"
  local staging="$2"
  # A Windows build names the binary with the extension, and the caller passes
  # the path without it, exactly as the smoke test resolves it.
  if [ ! -f "$binary" ] && [ -f "${binary}.exe" ]; then
    binary="${binary}.exe"
  fi
  [ -f "$binary" ] || fail "no built binary at ${1}"
  mkdir -p "$staging"
  binary=$(cd "$(dirname "$binary")" && pwd)/$(basename "$binary")
  staging=$(cd "$staging" && pwd)

  local root
  root=$(cd "$(dirname "$0")/.." && pwd)

  local name="openpapir"
  case "$binary" in
    *.exe) name="openpapir.exe" ;;
  esac
  cp "$binary" "${staging}/${name}"
  cp "${root}/LICENSE" "${root}/README.md" "${root}/CHANGELOG.md" "$staging"

  mkdir -p "${staging}/completions" "${staging}/man/man1"
  local entry shell file
  for entry in $SHELLS $MORE_SHELLS; do
    shell="${entry%%:*}"
    file="${entry#*:}"
    "$binary" completions "$shell" > "${staging}/completions/${file}"
  done
  "$binary" manpage > "${staging}/${MAN_PAGE}"

  check_present "${staging}/${name}" "$name"
  check_present "${staging}/LICENSE" "LICENSE"
  check_present "${staging}/README.md" "README.md"
  check_present "${staging}/CHANGELOG.md" "CHANGELOG.md"
  for entry in $SHELLS $MORE_SHELLS; do
    file="${entry#*:}"
    check_present "${staging}/completions/${file}" "completions/${file}"
  done
  check_present "${staging}/${MAN_PAGE}" "$MAN_PAGE"

  # clap writes a two-line quote-escaping preamble before the header, so the
  # header is looked for in the first lines rather than on the first line. It
  # has to be the first roff header request in the stream and has to name this
  # command in section 1.
  local header
  header=$(grep -n -m 1 '^\.TH' "${staging}/${MAN_PAGE}" || true)
  [ -n "$header" ] || fail "the man page carries no .TH header"
  case "$header" in
    [1-5]:.TH\ openpapir\ 1*) ;;
    *) fail "the man page does not start with a .TH openpapir 1 header" ;;
  esac

  echo "staged the archive contents in ${staging}"
}

main "$@"
