#!/usr/bin/env bash
# Stage the contents of one release archive, then check the staged layout.
#
# The release workflow calls this once per target, with the binary it just
# built, and the CI test job calls it on every pull request with the binary
# from its own release build. Both call this one script, so the layout a
# release ships is the layout every pull request exercises, without a tag.
#
# The completion scripts and the man page are generated by the built binary of
# that target, from the command definition it was built with, so they can
# never describe commands the archived binary does not have.
#
# Usage:
#   scripts/package-release.sh <binary> <staging directory>
#   scripts/package-release.sh --describe
#   scripts/package-release.sh --describe --paths [<binary name>]
#
# `--describe` prints the sentence that names what an archive holds, and
# `--describe --paths` prints the same contents as one relative path per line.
# Both are generated from the tables the staging loop reads, so neither the
# sentence the release job prints nor the listing CI diffs against the staged
# tree can name a layout other than the one that was staged.
set -euo pipefail

# One table of shells drives everything. The staging loop generates one
# completion script per row, `--describe` names the shells from it, and
# `--describe --paths` lists the files from it, so adding or removing a shell
# changes the staging, the sentence, and the listing together. The file names
# are the ones each shell looks for, which is what the manual instructions in
# README.md redirect to.
readonly COMPLETIONS="\
bash:openpapir.bash
zsh:_openpapir
fish:openpapir.fish
powershell:_openpapir.ps1
elvish:openpapir.elv"
# The documents copied from the built tree, in the order they are listed.
# THIRD-PARTY-NOTICES.md is the attribution the dependency licences require;
# it is generated by scripts/third-party-notices.py and committed, so an
# archive is staged from the tree like the other three and no generator runs
# here.
readonly DOCUMENTS="LICENSE THIRD-PARTY-NOTICES.md README.md CHANGELOG.md"
readonly MAN_PAGE="man/man1/openpapir.1"

fail() {
  echo "package-release: $1" >&2
  exit 1
}

# The words of a list, each in backticks, joined for prose. The last separator
# is given by the caller, so a list can read `a`, `b`, and `c` or plainly
# `a`, `b`, `c`.
prose_list() {
  local last="$1"
  shift
  local word total=0 count=0 list=""
  for word in "$@"; do
    total=$((total + 1))
  done
  for word in "$@"; do
    count=$((count + 1))
    if [ "$count" -eq 1 ]; then
      list="\`${word}\`"
    elif [ "$count" -eq "$total" ]; then
      list="${list}${last}\`${word}\`"
    else
      list="${list}, \`${word}\`"
    fi
  done
  printf '%s' "$list"
}

# The shells of the table, so the sentence names exactly the shells the
# staging loop writes a script for.
shell_list() {
  local entry shells=()
  for entry in $COMPLETIONS; do
    shells+=("${entry%%:*}")
  done
  prose_list ", and " "${shells[@]}"
}

describe() {
  local shells documents
  shells=$(shell_list)
  # shellcheck disable=SC2086 # the table is a deliberate word list.
  documents=$(prose_list ", " $DOCUMENTS)
  cat <<EOF
Each archive holds the \`openpapir\` binary, ${documents}, a shell completion
script for each of ${shells} under \`completions/\`, and the man page at
\`${MAN_PAGE}\`, under one directory named
\`openpapir-<version>-<target>\`. The completion scripts and the man page are
generated by the built binary of that target. The \`<archive>.sha256\` file
beside each archive covers the archive as a whole, so it covers them too.
EOF
}

# Every path an archive holds, relative to its one directory, one per line and
# in a stable order. The binary is named by the caller, because a Windows
# build stages `openpapir.exe` where the others stage `openpapir`.
describe_paths() {
  local binary="${1:-openpapir}" entry document
  printf '%s\n' "$binary"
  for document in $DOCUMENTS; do
    printf '%s\n' "$document"
  done
  for entry in $COMPLETIONS; do
    printf 'completions/%s\n' "${entry#*:}"
  done
  printf '%s\n' "$MAN_PAGE"
}

# Every staged file has to exist, be a regular file rather than a link, and
# hold something: an empty completion script is a generator that failed
# quietly, not a shipped file.
check_present() {
  local path="$1"
  [ ! -L "$path" ] || fail "a symbolic link stands in the staged archive: $2"
  [ -f "$path" ] || fail "missing from the staged archive: $2"
  [ -s "$path" ] || fail "empty in the staged archive: $2"
}

# The destination has to be a directory this run can fill on its own. A
# symbolic link is refused, so nothing is written through one, and so is a
# directory that already holds files, so one staging cannot mix into another.
# The check runs before the first write.
check_staging() {
  local staging="$1"
  [ ! -L "$staging" ] || fail "the staging path is a symbolic link"
  if [ -e "$staging" ]; then
    [ -d "$staging" ] || fail "the staging path is not a directory"
    [ -z "$(ls -A "$staging")" ] ||
      fail "the staging directory already holds files"
  fi
}

main() {
  if [ "${1:-}" = "--describe" ]; then
    if [ "${2:-}" = "--paths" ]; then
      describe_paths "${3:-openpapir}"
    else
      describe
    fi
    return 0
  fi
  [ "$#" -eq 2 ] || fail "usage: package-release.sh <binary> <staging directory>"

  local binary="$1"
  local staging="$2"
  # A Windows build names the binary with the extension, and the caller passes
  # the path without it, exactly as the smoke test resolves it.
  if [ ! -f "$binary" ] && [ -f "${binary}.exe" ]; then
    binary="${binary}.exe"
  fi
  [ -f "$binary" ] || fail "no built binary at ${1}"
  check_staging "$staging"
  mkdir -p "$staging"
  binary=$(cd "$(dirname "$binary")" && pwd -P)/$(basename "$binary")
  staging=$(cd "$staging" && pwd -P)

  local root
  root=$(cd "$(dirname "$0")/.." && pwd -P)

  local name="openpapir"
  case "$binary" in
    *.exe) name="openpapir.exe" ;;
  esac
  cp "$binary" "${staging}/${name}"
  local document
  for document in $DOCUMENTS; do
    cp "${root}/${document}" "${staging}/${document}"
  done

  mkdir -p "${staging}/completions" "${staging}/man/man1"
  local entry shell file
  for entry in $COMPLETIONS; do
    shell="${entry%%:*}"
    file="${entry#*:}"
    "$binary" completions "$shell" > "${staging}/completions/${file}"
  done
  "$binary" manpage > "${staging}/${MAN_PAGE}"

  # The same listing `--describe --paths` prints, so the layout that is
  # checked here and the layout that is described are one table.
  local path
  while IFS= read -r path; do
    check_present "${staging}/${path}" "$path"
  done < <(describe_paths "$name")

  # clap writes a two-line quote-escaping preamble before the header, so the
  # header is looked for in the first lines rather than on the first line. It
  # has to be the first roff header request in the stream and has to name this
  # command in section 1.
  local header
  header=$(grep -n -m 1 '^\.TH' "${staging}/${MAN_PAGE}" || true)
  [ -n "$header" ] || fail "the man page carries no .TH header"
  case "$header" in
    [1-5]:.TH\ openpapir\ 1*) ;;
    *) fail "the man page does not start with a .TH openpapir 1 header" ;;
  esac

  echo "staged the archive contents in ${staging}"
}

main "$@"
