#!/usr/bin/env python3
"""Generate the third-party notice that every release archive carries.

The BSD-3-Clause licences this repository allows require attribution, and so
do MIT and Apache-2.0. A release therefore ships a list of every dependency
it links, with the version and the licence each one declares.

The list is read from `cargo metadata`, which resolves the checked-in
`Cargo.lock`, so this script needs cargo and nothing else: no build-time
dependency is added to the workspace and no extra tool has to be installed to
land a change. `cargo-about` and similar tools produce a richer notice by
embedding every licence text; they stay optional, and the committed file is
the one produced here.

The graph is walked from the workspace members over normal and build edges
only, with every feature enabled and no platform filter, so the result is a
superset of what any one release target links. Development-only dependencies
are excluded: they are not in a shipped binary.

Usage:
  scripts/third-party-notices.py            write THIRD-PARTY-NOTICES.md
  scripts/third-party-notices.py --check    fail if the committed file is stale

`--check` is what `scripts/check.sh` and CI run, so a dependency added,
removed, or moved to another version fails the pull request that did it until
the notice is regenerated.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTICE = ROOT / "THIRD-PARTY-NOTICES.md"

HEADER = """# Third-party notices

openPapir is distributed under the MIT licence in `LICENSE`. A release archive
also carries the compiled code of the dependencies listed below, each under
its own licence, and this file is the attribution those licences ask for.

The list is generated by `scripts/third-party-notices.py` from
`cargo metadata` and the checked-in `Cargo.lock`. It is not edited by hand:
the check that runs in `scripts/check.sh` and in CI regenerates it and fails
when the committed file differs. It covers the normal and build dependencies
of both workspace crates, with every feature enabled and no platform filter,
so it is a superset of what any single release target links; dependencies used
only by tests and other development targets are not listed, because no shipped
binary holds them.

A licence expression is the one the crate itself declares. Where it offers a
choice, openPapir relies on the terms of any one of the named licences. The
full text of each licence is in the source of the crate it covers, which
`cargo metadata` resolves from the same lockfile as this list.

The allowed set of licence identifiers, and the reason each one is allowed, is
in `deny.toml`, which `cargo deny check licenses` enforces on every pull
request.

| Crate | Version | Licence |
| --- | --- | --- |
"""


def metadata():
    """Return the resolved workspace metadata as parsed JSON."""
    output = subprocess.check_output(
        [
            "cargo",
            "metadata",
            "--format-version",
            "1",
            "--all-features",
            "--locked",
        ],
        cwd=ROOT,
        text=True,
    )
    return json.loads(output)


def shipped(data):
    """Return the package ids reached from the workspace over non-dev edges."""
    nodes = {node["id"]: node for node in data["resolve"]["nodes"]}
    members = set(data["workspace_members"])
    seen = set(members)
    queue = list(members)
    while queue:
        node = nodes.get(queue.pop())
        if node is None:
            continue
        for dep in node["deps"]:
            kinds = dep.get("dep_kinds") or [{"kind": None}]
            if all(kind.get("kind") == "dev" for kind in kinds):
                continue
            if dep["pkg"] in seen:
                continue
            seen.add(dep["pkg"])
            queue.append(dep["pkg"])
    return seen - members


def licence(package):
    """Return the licence expression a package declares, as one cell."""
    expression = package.get("license")
    if expression:
        return " ".join(expression.split())
    if package.get("license_file"):
        return f"See `{package['license_file']}` in the crate source"
    raise SystemExit(
        f"{package['name']} {package['version']} declares no licence; "
        "the notice cannot attribute it, so the dependency set must change"
    )


def render(data):
    """Return the notice document for the resolved metadata."""
    packages = {package["id"]: package for package in data["packages"]}
    rows = sorted(
        (
            (packages[id]["name"], packages[id]["version"], licence(packages[id]))
            for id in shipped(data)
        ),
        key=lambda row: (row[0], row[1]),
    )
    lines = [
        f"| `{name}` | {version} | {expression} |"
        for name, version, expression in rows
    ]
    count = len(rows)
    crates = "crate" if count == 1 else "crates"
    tail = f"\nThe list holds {count} {crates}.\n"
    return HEADER + "\n".join(lines) + "\n" + tail


def main():
    arguments = sys.argv[1:]
    if arguments not in ([], ["--check"]):
        print(f"usage: {Path(__file__).name} [--check]", file=sys.stderr)
        return 2
    document = render(metadata())
    if arguments == ["--check"]:
        current = NOTICE.read_text(encoding="utf-8") if NOTICE.exists() else ""
        if current == document:
            print("Third-party notices are current")
            return 0
        print(
            "THIRD-PARTY-NOTICES.md is out of date. Regenerate it with "
            "scripts/third-party-notices.py and commit the result.",
            file=sys.stderr,
        )
        return 1
    NOTICE.write_text(document, encoding="utf-8")
    print(f"Wrote {NOTICE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
